### ISSUE TITLE
Question: Does web.telemetry-path regard uwsgi_exporter or uWSGI itself?

### ISSUE THREAD

**Issue by rszalski** [timonwong/uwsgi_exporter#25]
I got confused when setting the `--web.telemetry-path` option. The README says it's a _"Path under which to expose metrics."_ which (to me at least) means that metrics *will* be exposed by *uwsgi_exporter* at this path. However, this doesn't seem to be the case since I got stuck when I set this path to `/metrics`&mdash;uwsgi_exporters's output was empty. Only when I removed it `uwsgi_exporter` started scraping stats from the uWSGI daemon (exposed over HTTP under `/` path. This seems like the `telemetry-path` applies to the `uWSGI` daemon and not the exporter.

If this is the case a good idea would be to reword this in the README as it might be a stumbling block for new users.

**Comment by timonwong** [comment]
It regards uwsgi exporter only.
The `--web.telemetry-path` flag is just a convention for almost all prometheus exporters to expose metrics under this path.

**Comment by rszalski** [comment]
Thanks for clarification, this makes sense. I've retested this once again and seems that my confusion arose from missing the `/` in the `--web.telemetry-path` argument. If you don't provide the slash it won't serve you metrics up.

Still, explicitly mentioning this in the docs or issuing a warning when launching would be nice. Other than that, there is nothing else to do here :)
