### ISSUE TITLE
too much data

### ISSUE THREAD

**Issue by BaronMsk** [timonwong/uwsgi_exporter#34]
It seems the exporter is giving too much data

**uwsgi.ini**
```
[uwsgi]
master = true
socket = :3000
listen = 1024

disable-logging = true
logger = syslog:ugc,local0

pythonpath = /var/www/
env = WSGI_CONF=production
module = ugc.wsgi:uwsgi_app()
processes = 150
need-app = true
lazy = true
gevent = 256
buffer-size  = 8192
post-buffering = 8192
reload-mercy = 5

; ignore close errors
ignore-sigpipe = true
ignore-write-errors = true
disable-write-exception = true

stats = /run/ugc/stats
```

```
# curl -O localhost:9117/metrics
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27.4M  100 27.4M    0     0  14.8M      0  0:00:01  0:00:01 --:--:-- 14.8M
```

**Comment by timonwong** [comment]
Try with `--collect.cores=false`

**Comment by BaronMsk** [comment]
@timonwong I am glad that you said about this flag and it does not work ```# uwsgi_exporter --stats.uri=unix:///var/run/ugc/stats     --web.listen-address=:9117 --stats.timeout=5s --collect.cores=false
uwsgi_exporter: error: unexpected false, try --help```

**Comment by BaronMsk** [comment]
@timonwong it seems it should work differently,  I prepared an MR https://github.com/timonwong/uwsgi_exporter/pull/35

**Comment by timonwong** [comment]
@BaronMsk v1.0.0 was released with your changes, thanks:)
