### ISSUE TITLE
Request Grafana dashboard for uwsgi_exporter

### ISSUE THREAD

**Issue by alochym01** [timonwong/uwsgi_exporter#41]
i need dashboard for uwsgi_exporter

Could you please share it with me

**Comment by arthurlogilab** [comment]
Hey, we deployed this exporter on our uwsgi apps with little modifications, thanks for a nice project. Having the docker image enabled us to easily add it to our kubernetes deployments. We're still tinkering, but started a grafana dashboard that looks like this : 

![Screenshot from 2021-05-25 15-01-12](https://user-images.githubusercontent.com/445200/119502459-3d720e00-bd6a-11eb-81da-d48f05fb82c9.png)


https://grafana.com/grafana/dashboards/3435 seems to be a different implementation and doesn't seem to "pick up" the metrics. Maybe it can serve as inspiration for a shared dashboard for this exporter. 

@alochym01 did you have more specifics on what you wanted to read in the dashboard ?

**Comment by alochym01** [comment]
thank you @arthurlogilab @Kl0ven
